# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Suhail-macOS
  vmImage: macOS-13

steps:
- script: |
    java -version
    echo "JAVA_HOME_21_X64 fixing"
    JAVA_HOME_21_X64='/usr/local/Cellar/openjdk/21.0.1/libexec/openjdk.jdk/Contents/Home'
    echo $JAVA_HOME_21_X64
    export JAVA_HOME_21_X64

- task: Maven@3
  inputs:
    mavenPomFile: 'complete/pom.xml'
    mavenOptions: '-Xmx3072m'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- script: |
    java /Users/suhailsinghbains/Downloads/myagent/_work/1/s/complete/target/spring-boot-complete-0.0.1-SNAPSHOT.jar
    echo "DONE"

